services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80" # Expose port 80 of the container to port 3000 on the host
    environment:
      - API_URL=http://server:8080 # URL de l'API du serveur
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose port 8080 of the container to port 8080 on the host
