services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:8080"
        VITE_USE_MOCK: "false"
    ports:
      - "80:80" # Expose port 80 of the container to port 3000 on the host
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose port 8080 of the container to port 8080 on the host
